Corrected error messages.

diff --git a/cvcexpand b/cvcexpand
--- a/cvcexpand
+++ b/cvcexpand
@@ -693,8 +693,8 @@ function processLine {
                 elif [ "${values[0]}" ]
                 then
                     (>&2 echo "WARNING: In file: '${targetCVCFile}':")
-                    (>&2 echo "Alias '+RELEASEID' requires exactly two arguments. The following line will be ignored:")
                     (>&2 echo "${1}")
+                    (>&2 echo "Alias '+RELEASEID' requires exactly two arguments. The following line will be ignored:")
                 fi
 
             # +RELEASESOURCE=ReleaseSource
@@ -884,7 +884,7 @@ function processLine {
         CVCINTERNAL_OUTPUTBUFFER+=("$line")
         
     else
-        >&2 echo "ERROR: Invalid line in file '${1}':"
+        >&2 echo "ERROR: Invalid line in file '${targetCVCFile}':"
         >&2 echo "${line}"
         [[ "${BASH_SOURCE[0]}" != "${0}" ]] && return 6 || exit 6
     fi
